config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:new, :create, :delete]
  resources :reviews, only: [:new, :create]
  resources :films, only: [:index, :show]
  resources :categories, only: [:show, :index]
  resources :users, only: [:show, :new, :create]

  delete 'comments/:id' => 'comments#delete'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/winners', to: 'pages#winners'

  root 'categories#index'
  resources :films, only: [:index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :films

  def sort_by_rating
    self.films.sort_by{|film| film.total_reviews}.reverse
  end

  def winner
    sort_by_rating.first
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user_id, :review_id, presence: true

  belongs_to :review
  belongs_to :user
end

app/models/film.rb
class Film < ActiveRecord::Base
  validates :title, :description, :writers, :actors, :director, :category_id, presence: true

  has_many :reviews
  belongs_to :category
  has_many :users, through: :reviews

def user_reviews
  user_reviews = self.reviews.select{|review| review.user.judge_status==false}
  review_sum = user_reviews.map{|review| review.star_value}.reduce(:+)
  user_average = review_sum / user_reviews.length
end

def judge_reviews
  judge_reviews = self.reviews.select{|review| review.user.judge_status==true}
  review_sum = judge_reviews.map{|review| review.star_value}.reduce(:+)
  judge_average = review_sum / judge_reviews.length
end

def user_reviews_exist?
  true if self.reviews.select{|review| review.user.judge_status==false}.length > 0
end

def judge_reviews_exist?
  true if self.reviews.select{|review| review.user.judge_status==true}.length > 0
end

def total_reviews
  if judge_reviews_exist? && user_reviews_exist?
      (self.judge_reviews * 0.8) + (self.user_reviews * 0.2)
  elsif user_reviews_exist?
    self.user_reviews
  elsif judge_reviews_exist?
    self.judge_reviews
  else
    0
  end
end

def round_to_fifth
  ((self.total_reviews) * 2).round / 2.0
end

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title, :body, :star_value, :user_id, :film_id,  presence: true

  has_many :comments
  belongs_to :user
  belongs_to :film
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true
  validates :email, format: {with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}, on: :create

  has_many :reviews
  has_many :comments
  has_many :films, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
       current_user != nil
    end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_films = @category.sort_by_rating
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
   @comment = Comment.new
   @review_id = params[:review_id]
   if request.xhr?
     render partial: 'comments/new', locals: {comment: @comment}
   end
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render :json => {count: count} }
      end
      # redirect_to "/films/#{@comment.review.film.id}"
    else
      render 'new'
    end
  end

  def delete
    comment = Comment.find_by(id: params[:id])
    film_id = comment.review.film.id
    comment.destroy
    redirect_to "/films/#{film_id}"
  end

 private
    def comment_params
      params.require(:comment).permit(:body,:user_id, :review_id)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def index
    @films = Film.all
  end

  def show
    @film = Film.find_by(id: params[:id])

    # @category = Category.find(params[:category_id])
  end



# private

#   def film_params
#     params.require(:film).permit(:id)
#   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def winners
    @categories = Category.all
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
     @review = Review.new
     @film_id = params[:film_id]
     if request.xhr?
      render partial: 'reviews/new', locals: {user: @user, review: @review}
     end
  end

  def create
     @review = Review.new(review_params)
    if @review.save
      redirect_to "/films/#{@review.film.id}"
    else
      render 'new'
    end
  end

 private
    def review_params
      params.require(:review).permit(:title, :body, :star_value, :user_id, :film_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:sessions][:username])
    if @user && @user.authenticate(params[:sessions][:password])
      session[:user_id] = @user.id
      redirect_to categories_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to categories_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @review = Review.where(user_id: @user.id, )
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
    if @user.save
      redirect_to categories_path
      session[:user_id] = @user.id
    else
      render 'new'
    end
  end

 private
    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1 id="festival-category-header">FESTIVAL CATEGORIES</h1>

<div class="hidden">
    <ul class="list">
      <% @categories.each do |category| %>
      <li class="category-names"><a href="/categories/<%=category.id%>"><div class="category-div">
        <span class="category-span">
        <%= category.name.upcase %>
        </span>
        </div></a></li>
      <% end %>
    </ul>
</div>

<div id="button-div">
  <a href="/winners"><button id="winner-button">WINNING FILMS</button></a>
</div>

app/views/categories/show.html.erb
<div>

  <h1><%= @category.name.upcase %></h1>

    <ul id="film-list">
      <% @category_films.each do |film| %>
      <div class="film-div">
      <li> <h3><%= link_to "#{film.title.upcase}", film_path(film) %></h3></li>
      <li> <span class="underline-span">Description:</span> <%= film.description%></li><br>
      <li> <span class="underline-span">Rating:</span> <%= film.round_to_fifth%> stars</li>
       </div>
      <% end %>

    </ul>


    <%= link_to "Back to category listing", categories_path %>

</div>

app/views/comments/_delete.html.erb
<form action="/comments/<%=comment.id%>" method="post">
  <%=token_tag%>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Comment">
</form>

app/views/comments/_form.html.erb
<%= form_for comment do |f| %>
  <% if comment.errors.any? %>
    <p><%=pluralize(comment.errors.count, "error") %> prevented this post from saving.</p>

    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

  <%end%>

  <p>
    <%=f.label :body %><br>
    <%=f.text_field :body %>
  </p>

   <p>
    <%=f.hidden_field :user_id, :value => current_user.id %><br>
  </p>

     <p>
    <%=f.hidden_field :review_id, :value => @review_id %><br>
  </p>
  </p>

   <p>
    <%=f.submit %>
  </p>
<% end %>

app/views/comments/_new.html.erb
<%= form_for comment, html: {class: 'new'} do |f| %>
  <% if comment.errors.any? %>
    <p><%=pluralize(comment.errors.count, "error") %> prevented this post from saving.</p>

    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  <%end%>

  <p>
    <%=f.label :body %><br>
    <%=f.text_field :body %>
  </p>

   <p>
    <%=f.hidden_field :user_id, :value => current_user.id %><br>
  </p>

  <p>
    <%=f.hidden_field :review_id, :value => @review_id %><br>
  </p>
  </p>

   <p class="submit-comment">
    <%=f.submit %>
  </p>
<% end %>

app/views/comments/_show.html.erb
<p>posted by: <%= comment.user.username %></p>
<p>comment: <%= comment.body %></p>
<%if logged_in? && current_user == comment.user%>
  <%=render partial: 'comments/delete', locals: {comment: comment}%>
<%end%>

app/views/comments/new.html.erb
<h2>Leave A Comment</h2>

<%=render partial: 'comments/new', locals: {comment: @comment}%>

app/views/films/index.html.erb
<h1 id="film-index">LES Film Index</h1>


<div class="hidden" id="movie-title-div">
<% @films.each do |film| %>

    <%= link_to film.title, film_path(film) %> |
<% end %>
  </div>

app/views/films/show.html.erb
<h1><%= @film.title.upcase %></h1>

<% if @film.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@film.errors.count, "error") %></h2>

    <ul>
    <% @film.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="film-info-div">
  <ul>
    <p><span class="underline-span">Description:</span> <%= @film.description %></p>
      <p><li><span class="underline-span">Written by:</span> <%= @film.writers %></li></p>
      <li><p><span class="underline-span">Starring:</span> <%= @film.actors %></li></p>
      <li><p><span class="underline-span">Directed by:</span> <%= @film.director %></li></p>
      <li><p><span class="underline-span">Rating:</span> <%= @film.round_to_fifth %></li></p>
    </div>
  </ul>

</div>

<hr>
  <h1>REVIEWS</h1>
<div class="reviews-container">
    <%if logged_in?%>
      <button class="review-button reviews"><%= link_to 'REVIEW THIS FILM', "/reviews/new?film_id=#{@film.id}", id: "#{@film.id}" %></button>
    <%end%>


    <%@film.reviews.each do |review|%>
      <%=render partial: 'reviews/show', locals: {review: review}%>
    <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LesFilmFest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Didact+Gothic' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="wrapper">
  <header>

    <nav id="user-nav">
      <ul class="list" id="index">
      <% if logged_in? %>
          <li id="main-header">LES FILM FEST 2016</li>

          <div class="nav-div"><li><%= link_to 'Home', categories_path %></li></div>
           <div class="nav-div"><li><%= link_to 'Film Categories', categories_path %></li></div>
          <div class="nav-div"><li><%= link_to "All Films", films_path %></li></div>
          <div class="nav-div"><li class="link"><%= link_to "My Page", user_path(current_user) %></li></div>
          <div class="nav-div"><li><%= link_to 'Log Out', logout_path, method: "delete" %></li></div>
      <% else %>
          <li id="main-header">LES FILM FEST 2016</li>
          <div class="nav-div"><li><%= link_to 'Home', categories_path %></li></div>
          <div class="nav-div"><li><%= link_to 'Film Categories', categories_path %></li></div>
          <div class="nav-div"><li><%= link_to "All Films", films_path %></li></div>
          <div class="nav-div"><li><%= link_to 'Sign Up', new_user_path %></li></div>
          <div class="nav-div"><li><%= link_to 'Login', login_path %></li></div>
      <% end %>
      </ul>
    </nav>
  </header>



<%= yield %>
<div class="push"></div>
</div>
 <div class="foot">
  <footer>
    <ul id="footer-list">
      <li class="footer-text">(C) Megan, Christyn, Brian, Adam</li>
      <li class="footer-text"> |</li>
      <li class="footer-text"> <a href="https://github.com/ChristynBudzyna/les-film-fest-3">Our Code</a></li>
    </ul>
  </footer>
</div>
</body>
</html>

app/views/pages/winners.html.erb
<div id="winner-page">
<h1 id="winner-header">W I N N E R S</h1>

<% @categories.each do |category| %>

<li class="category-names">
  <div class="category-div-winner">
    <span class="category-span-winner">
      <%= category.name.upcase %>
    </span>
  </div>
</li>

  <div class="hidden">
    <h2 class="winner-title"><%= category.winner.title.upcase %></h2><br>
  </div>
<% end %>
</div>

app/views/reviews/_form.html.erb
<%= form_for review do |f| %>
  <% if review.errors.any? %>
    <p><%=pluralize(user.errors.count, "error") %> prevented this post from saving.</p>

    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

  <%end%>

  <p>
    <%=f.label :title %><br>
    <%=f.text_field :title %>
  </p>

  <p>
    <%=f.label :body %><br>
    <%=f.text_field :body %>
  </p>

  <p>
    <%=f.label :star_value %><br>
    <%=f.select :star_value, [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5] %>
  </p>

   <p>
    <%=f.hidden_field :user_id, :value => current_user.id %><br>
  </p>

     <p>
    <%=f.hidden_field :film_id, :value => @film_id %><br>
  </p>
  </p>

   <p>
    <%=f.submit %>
  </p>
<% end %>

app/views/reviews/_new.html.erb
<%= form_for review do |f| %>
  <% if review.errors.any? %>
    <p><%=pluralize(user.errors.count, "error") %> prevented this post from saving.</p>

    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

  <%end%>

  <p>
    <%=f.label :title %><br>
    <%=f.text_field :title %>
  </p>

  <p>
    <%=f.label :body %><br>
    <%=f.text_field :body %>
  </p>

  <p>
    <%=f.label :star_value %><br>
    <%=f.select :star_value, [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5] %>
  </p>

   <p>
    <%=f.hidden_field :user_id, :value => current_user.id %><br>
  </p>

     <p>
    <%=f.hidden_field :film_id, :value => @film_id %><br>
  </p>
  </p>

   <p>
    <%=f.submit %>
  </p>
<% end %>

app/views/reviews/_show.html.erb
<h2 class="review-title-header"><%=review.title.upcase%></h2>
<p><%=review.body%></p>


<h3>COMMENTS</h3>
<div class="comment-holder" id="<%=review.id%>">
  <% review.comments.each do |comment| %>
    <%=render partial: 'comments/show', locals: {comment: comment}%>
  <% end %>


<%if logged_in?%>

<button class="review-button comments" id="button<%=review.id%>">
  <%= link_to 'COMMENT ON THIS REVIEW', "/comments/new?review_id=#{review.id}", id: "#{review.id}"%></button>
<%end%>
</div>

app/views/reviews/new.html.erb
<h2>Leave A Review</h2>

<%=render partial: 'reviews/new', locals: {user: @user, review: @review}%>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <p><%=pluralize(@user.errors.count, "error") %> prevented this post from saving.</p>

    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

  <%end%>
<div id='registration' class='login_or_register'>
  <p>
    <%=f.label :username %><br>
    <%=f.text_field :username %>
  </p>

  <p>
    <%=f.label :email %><br>
    <%=f.text_field :email %>
  </p>

  <p>
    <%=f.label :password %><br>
    <%=f.password_field :password %>
  </p>

   <p>
    <%=f.submit %>
  </p>
</div>
<% end %>

app/views/users/show.html.erb
<div>

  <div id='user-name'>
    <h1><%= current_user.username.capitalize %></h1>
    <% if current_user.judge_status == true %>
      <h3> Hey there, judge! </h3>
    <% else %>
    <% end %>
  </div>

  <div class="hidden" id='user-reviews'>
    <h3><%= current_user.username.capitalize %> has reviewed <%= current_user.reviews.count %> films: </h3>
        <% current_user.reviews.each do |review| %>
          <h3><%= link_to review.film.title, film_path(review.film) %></h3>
      <% end %>
  </div>

    <%= link_to "Category listing", categories_path %>

</div>